apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static-site
  template:
    metadata:
      labels:
        app: nginx-static-site
    spec:
      nodeSelector:
        kubernetes.io/hostname: "worker1"
      initContainers:
        - name: fetch-site
          image: minio/mc
          env:
            - name: MC_HOST_minio
              value: "http://minioadmin:minioadmin123@minio-svc:9000"
          command: ["mc"]
          args: ["cp", "--recursive", "minio/msbblt/", "/site/"]
          volumeMounts:
            - name: site-data
              mountPath: /site
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: site-data
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
      volumes:
        - name: site-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static-site
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx-static-site
