apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static-site
  template:
    metadata:
      labels:
        app: nginx-static-site
    spec:
      nodeSelector:
        kubernetes.io/hostname: "server2"          ## Bu kısmı isterseniz kaldırabilirsiniz istersenizde Nginx'in çalışmasını istediğiniz node'a göre güncellersiniz
      containers:
        - name: nginx
          image: msbblttt/nginx-static-site:11
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static-site
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-static-site
